# Make sure path includes our local bin directory
path+=("$HOME/bin" "$HOME/.local/bin")

# Use vi mode
bindkey -v

# Use 0.1 second esc key timeout instead of the default 0.4 second timeout
export KEYTIMEOUT=1

# Vi mode is cool and all, but I do like ctrl+r to search history
bindkey '^r' history-incremental-search-backward

# Backspace is also nice to have
bindkey '^?' backward-delete-char

# We should use (n)vim for our editor, or fall back to vi since it's
# [defined by posix](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/vi.html)
# and therefore very likely to be on the machine we're using.
if hash nvim 2>/dev/null; then
    export EDITOR="nvim"
elif hash vim 2>/dev/null; then
    export EDITOR="vim"
else
    export EDITOR="vi"
fi

# If we have nvim installed (we should), use it over vim seamlessly
if type "nvim" > /dev/null; then
    alias vim="nvim"
fi

# Speaking of aliases, lets be sure they're tab-completable
setopt COMPLETEALIASES

# Use vi mode in pretty much any tool that uses GNU Readline. We use an ohmyzsh
# plugin for zsh vi mode.
set editing-mode vi

# Share history between shells
setopt SHARE_HISTORY

# Don't overwrite history either
setopt APPEND_HISTORY

# Save when and how long a command was run
setopt EXTENDED_HISTORY

# Don't save next line if it is the same as prev
setopt HISTIGNOREDUPS

# Pretty    obvious,    right?
setopt HIST_REDUCE_BLANKS

# Shut up, computer
setopt NO_BEEP

# Disable x11's ugly passphrase prompt
unset SSH_ASKPASS

# Disables ctrl-s (stupid nonsense that "pauses" screen)
setopt NO_FLOW_CONTROL

# Configure golang stuff
export GOPATH="${HOME}/.go/"
path+=("$GOPATH/bin")

# Configure rust stuff
source $HOME/.cargo/env

# Configure k8s stuff
alias k=kubectl
source <(kubectl completion bash)
complete -F __start_kubectl k

# Activate a few autocomplete plugins that were installed by ansible
source "$HOME/.zsh_plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh"
source "$HOME/.zsh_plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"

# Configue zsh-autocomplete
zstyle ':autocomplete:list-choices:*' max-lines 5
zstyle ':autocomplete:*' magic expand-history  # no auto-correct, only history
zstyle ':autocomplete:tab:*' completion select  # tab cycles matches
zstyle ':completion:list-expand:*' extra-verbose false  # less prompt

# Customize prompt
PROMPT="%F{black}%* %F{magenta}[%1~] %F{black}> %F{white}"
PROMPT2="%F{black}%_... %F{white}"

# If I'm at work, use some stuff to work with internal systems.
if [ -f $HOME/.zshrc.work ]; then
    source $HOME/.zshrc.work
fi
