# file: dotfiles.yml
- name: Set up local workstation
  hosts: local
  roles:
    - role: zsh
      tags:
        - zsh
    - role: nvim
      tags:
        - nvim
    - role: x
      tags:
        - x
    - role: newsboat
      tags:
        - newsboat
