---
# Install Xresources
- name: Check for existing Xresources file.
  stat:
    path: "{{ home_dir }}/.Xresources"
  register: xresources

- name: Back up existing Xresources file.
  when: xresources.stat.exists
  copy:
    src: "{{ home_dir }}/.Xresources"
    dest: "{{ home_dir }}/.Xresources.bak"

- name: Remove existing Xresources file.
  when: xresources.stat.exists
  file:
    state: absent
    path: "{{ home_dir }}/.Xresources"

- name: Render our Xresources template and install it.
  template:
    src: "{{ role_path }}/templates/Xresources"
    dest: "{{ home_dir }}/.Xresources"
