---
#- name: Check for oh-my-zsh installation
#  stat:
#    path: "{{ home_dir }}/.oh-my-zsh/"
#  register: oh_my_zsh_dir
#
#- name: Install oh-my-zsh
#  when: not oh_my_zsh_dir.stat.exists
#  raw: "sh -c \"$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)\""
#
- name: Create place to install plugins
  file:
    path: "{{ home_dir }}/.zsh_plugins/"
    state: directory
    recurse: yes
  register: zsh_plugins_dir

- name: Install zsh-autocomplete
  git:
    repo: "https://github.com/marlonrichert/zsh-autocomplete.git"
    version: master
    clone: yes
    update: yes
    force: yes
    dest: "{{ zsh_plugins_dir.path }}/zsh-autocomplete/"

- name: Install zsh-autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    version: master
    clone: yes
    update: yes
    force: yes
    dest: "{{ zsh_plugins_dir.path }}/zsh-autosuggestions/"

- name: Get latest fzf
  git:
    repo: "https://github.com/junegunn/fzf.git"
    version: master
    clone: yes
    update: yes
    force: yes
    depth: "1"
    dest: "{{ zsh_plugins_dir.path }}/fzf/"

- name: Install fzf
  shell: "{{ zsh_plugins_dir.path }}/fzf/install"

- name: Check for .zshrc
  stat:
    path: "{{ home_dir }}/.zshrc"
  register: zshrc

- name: Back up .zshrc
  when: zshrc.stat.exists
  copy:
    src: "{{ home_dir }}/.zshrc"
    dest: "{{ home_dir }}/.zshrc.bak"

- name: Copy .zshrc
  copy:
    src: "{{ role_path }}/files/zshrc"
    dest: "{{ home_dir }}/.zshrc"
