---
- name: "shell/tmux :: Create place to install configs"
  file:
    path: "{{ home_dir }}/.tmux/"
    state: directory
    recurse: yes
  register: tmux_config_dir
- name: "shell/tmux :: Create place to install plugins"
  file:
    path: "{{ tmux_config_dir.path }}/plugins/"
    state: directory
    recurse: yes
  register: tmux_plugins_dir
- name: "shell/tmux :: Install tpm (plugins!)"
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    clone: yes
    update: yes
    force: yes
    dest: "{{ tmux_plugins_dir.path }}/tpm/"
- name: "shell/tmux :: Copy tmux.conf"
  copy:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ tmux_config_dir.path }}/tmux.conf"
