---
# Attempt to install nvim
# TODO: implement, use e.g.
#   - include_tasks: setup-Archlinux.yml
#     when: ansible_os_family == 'Archlinux'

# TODO: correct config installation directory should be selected based on OS and set by installer subtask

# TODO: install nvim from src?
# TODO: install Plug https://github.com/junegunn/vim-plug
# TODO: install nerdfont
# TODO: install build essentials, tho somewhere else (brew install cmake autoconf automake libtool)
# TODO: install python providers: https://neovim.io/doc/user/provider.html  (since we have lang installation roles, we can count python as an expected prereq and just run it raw from this role)
- name: Create config directory
  file:
    path: "{{ home_dir }}/.config/nvim"
    state: directory
    recurse: yes
  register: nvim_config_dir

- name: Symlink init.vim file to the nvim config directory.
  file:
    src: "{{ role_path }}/files/init.vim"
    dest: "{{ nvim_config_dir.path }}/init.vim"
    state: link

# Install nvim theme file
- name: Create nvim theme directory
  file:
    path: "{{ nvim_config_dir.path }}/colors"
    state: directory
  register: nvim_themes_dir

- name: Render main theme template and install it.
  template:
    src: "{{ role_path }}/templates/main_theme.vim"
    dest: "{{ nvim_themes_dir.path }}/malwrar.vim"

# Install airline theme file
- name: Create airline theme directory
  file:
    path: "{{ nvim_config_dir.path }}/autoload/airline/themes"
    state: directory
  register: nvim_airline_themes_dir

- name: Render airline theme template and install it.
  template:
    src: "{{ role_path }}/templates/airline_theme.vim"
    dest: "{{ nvim_airline_themes_dir.path }}/malwrar.vim"

#- name: Install plugin manager
#  shell: 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
#       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Install plugins
- name: Install plugins 
  shell: "nvim +PlugInstall +PlugUpdate +PlugClean! +qall > /dev/null"
