---
# TODO: don't try to install if we're not on a platform newboat doesn't support
- name: Create config directory
  file:
    path: "{{ home_dir }}/.newsboat"
    state: directory
    recurse: yes
  register: nb_config_dir

# Install urls file
- name: Check for existing urls file.
  stat:
    path: "{{ nb_config_dir.path }}/urls"
  register: urls

- name: Back up existing urls file.
  when: urls.stat.exists
  copy:
    src: "{{ nb_config_dir.path }}/urls"
    dest: "{{ nb_config_dir.path }}/urls.bak"

- name: Remove existing urls file.
  when: urls.stat.exists
  file:
    state: absent
    path: "{{ nb_config_dir.path }}/urls"

- name: Copy urls file to the nvim config directory.
  copy:
    src: "{{ role_path }}/files/urls"
    dest: "{{ nb_config_dir.path }}/urls"

# Install config file
- name: Check for existing config file.
  stat:
    path: "{{ nb_config_dir.path }}/config"
  register: config

- name: Back up existing config file.
  when: config.stat.exists
  copy:
    src: "{{ nb_config_dir.path }}/config"
    dest: "{{ nb_config_dir.path }}/config.bak"

- name: Remove existing config file.
  when: config.stat.exists
  file:
    state: absent
    path: "{{ nb_config_dir.path }}/config"

- name: Copy config file to the nvim config directory.
  copy:
    src: "{{ role_path }}/files/config"
    dest: "{{ nb_config_dir.path }}/config"
